# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hook.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hook.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhook.proto\x12\x04hook\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x01\n\x07Message\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x03 \x01(\x04\x12\x11\n\tthread_id\x18\x04 \x01(\x04\x12\x0e\n\x06\x61uthor\x18\x05 \x01(\t\x12\x12\n\nauthor_url\x18\x08 \x01(\t\x12\x10\n\x08rep_name\x18\x06 \x01(\t\x12\x0f\n\x07rep_url\x18\x07 \x01(\t2C\n\x0bSendMessage\x12\x34\n\x0bSendMessage\x12\r.hook.Message\x1a\x16.google.protobuf.EmptyB\x04Z\x02./b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\002./'
  _globals['_MESSAGE']._serialized_start=50
  _globals['_MESSAGE']._serialized_end=198
  _globals['_SENDMESSAGE']._serialized_start=200
  _globals['_SENDMESSAGE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
