// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: hook.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         string                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	ChatId        uint64                 `protobuf:"varint,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ThreadId      uint64                 `protobuf:"varint,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	AuthorUrl     string                 `protobuf:"bytes,8,opt,name=author_url,json=authorUrl,proto3" json:"author_url,omitempty"`
	RepName       string                 `protobuf:"bytes,6,opt,name=rep_name,json=repName,proto3" json:"rep_name,omitempty"`
	RepUrl        string                 `protobuf:"bytes,7,opt,name=rep_url,json=repUrl,proto3" json:"rep_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_hook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_hook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_hook_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Message) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Message) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetThreadId() uint64 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *Message) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Message) GetAuthorUrl() string {
	if x != nil {
		return x.AuthorUrl
	}
	return ""
}

func (x *Message) GetRepName() string {
	if x != nil {
		return x.RepName
	}
	return ""
}

func (x *Message) GetRepUrl() string {
	if x != nil {
		return x.RepUrl
	}
	return ""
}

var File_hook_proto protoreflect.FileDescriptor

const file_hook_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hook.proto\x12\x04hook\x1a\x1bgoogle/protobuf/empty.proto\"\xda\x01\n" +
	"\aMessage\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\x04R\x06chatId\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\x04R\bthreadId\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"author_url\x18\b \x01(\tR\tauthorUrl\x12\x19\n" +
	"\brep_name\x18\x06 \x01(\tR\arepName\x12\x17\n" +
	"\arep_url\x18\a \x01(\tR\x06repUrl2C\n" +
	"\vSendMessage\x124\n" +
	"\vSendMessage\x12\r.hook.Message\x1a\x16.google.protobuf.EmptyB\x04Z\x02./b\x06proto3"

var (
	file_hook_proto_rawDescOnce sync.Once
	file_hook_proto_rawDescData []byte
)

func file_hook_proto_rawDescGZIP() []byte {
	file_hook_proto_rawDescOnce.Do(func() {
		file_hook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hook_proto_rawDesc), len(file_hook_proto_rawDesc)))
	})
	return file_hook_proto_rawDescData
}

var file_hook_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_hook_proto_goTypes = []any{
	(*Message)(nil),       // 0: hook.Message
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_hook_proto_depIdxs = []int32{
	0, // 0: hook.SendMessage.SendMessage:input_type -> hook.Message
	1, // 1: hook.SendMessage.SendMessage:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hook_proto_init() }
func file_hook_proto_init() {
	if File_hook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hook_proto_rawDesc), len(file_hook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hook_proto_goTypes,
		DependencyIndexes: file_hook_proto_depIdxs,
		MessageInfos:      file_hook_proto_msgTypes,
	}.Build()
	File_hook_proto = out.File
	file_hook_proto_goTypes = nil
	file_hook_proto_depIdxs = nil
}
